#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate embedded fallback blobs for Launcher UI icons (embedded in flash).

Reads files from assets_bin when present; otherwise emits visible placeholders:
- *.bin files: LVGL v9 lv_image_header_t (RGB565) + solid-fill bitmap (default 48×48).
  Under Launcher there is usually no `userdata` LittleFS partition, so embedded fallbacks are used—
  1×1 placeholders looked like “missing icons”; larger placeholders stay recognizable until you add real assets.
- *.png files: canonical minimal 1×1 PNG
"""
from __future__ import annotations

import argparse
import os
import struct
import sys
from pathlib import Path

LV_IMAGE_HEADER_MAGIC = 0x19
LV_COLOR_FORMAT_RGB565 = 0x12

# Filenames referenced by Launcher / StackChan UI (keep in sync with call sites).
MANIFEST = [
    "icon_ezdata.bin",
    "icon_controller.bin",
    "icon_dance.bin",
    "icon_sentinel.bin",
    "icon_bat_lightning.bin",
    "icon_wifi_low.bin",
    "icon_wifi_medium.bin",
    "icon_wifi_high.bin",
    "icon_wifi_slash.bin",
    "icon_bell.bin",
    "icon_home.bin",
    "setup_stackchan_front_view.bin",
    "icon_setup.bin",
    "icon_indicator_left.bin",
    "icon_indicator_right.bin",
    "app_center_bg.png",
    "icon_app_center.bin",
    "icon_ai_agent.bin",
]

# Canonical 67-byte 1×1 transparent PNG (from public-domain minimal PNG corpus).
MINI_PNG_1X1 = bytes(
    [
        0x89,
        0x50,
        0x4E,
        0x47,
        0x0D,
        0x0A,
        0x1A,
        0x0A,
        0x00,
        0x00,
        0x00,
        0x0D,
        0x49,
        0x48,
        0x44,
        0x52,
        0x00,
        0x00,
        0x00,
        0x01,
        0x00,
        0x00,
        0x00,
        0x01,
        0x08,
        0x06,
        0x00,
        0x00,
        0x00,
        0x1F,
        0x15,
        0xC4,
        0x89,
        0x00,
        0x00,
        0x00,
        0x0A,
        0x49,
        0x44,
        0x41,
        0x54,
        0x78,
        0x9C,
        0x63,
        0x00,
        0x01,
        0x00,
        0x00,
        0x05,
        0x00,
        0x01,
        0x0D,
        0x0A,
        0x2D,
        0xB4,
        0x00,
        0x00,
        0x00,
        0x00,
        0x49,
        0x45,
        0x4E,
        0x44,
        0xAE,
        0x42,
        0x60,
        0x82,
    ]
)


def _lvgl_rgb565_bin(w: int, h: int, rgb565_word: int) -> bytes:
    """LVGL v9 binary image: header + RGB565 pixels (native LE uint16 per pixel)."""
    magic = LV_IMAGE_HEADER_MAGIC
    cf = LV_COLOR_FORMAT_RGB565
    flags = 0
    stride = w * 2
    reserved2 = 0
    hdr = struct.pack("<I", magic | (cf << 8) | (flags << 16))
    hdr += struct.pack("<I", w | (h << 16))
    hdr += struct.pack("<I", stride | (reserved2 << 16))
    pixel_le = struct.pack("<H", rgb565_word & 0xFFFF)
    row = pixel_le * w
    pixels = row * h
    return hdr + pixels


def _rgb565_word_for_fname(fname: str) -> int:
    """Distinct saturated-ish RGB565 per filename."""
    s = sum(ord(c) for c in fname)
    x = (s * 7919) ^ (len(fname) * 65537)
    r5 = (x >> 10) & 0x1F
    g6 = (x >> 5) & 0x3F
    b5 = x & 0x1F
    if r5 + g6 + b5 < 10:
        return 0xF81F  # magenta if too dark
    return (r5 << 11) | (g6 << 5) | b5


def _lvgl_rgb565_placeholder(fname: str) -> bytes:
    return _lvgl_rgb565_bin(48, 48, _rgb565_word_for_fname(fname))


def _load_or_placeholder(assets_bin: Path, fname: str) -> bytes:
    path = assets_bin / fname
    if path.exists() and path.is_file():
        return path.read_bytes()
    lower = fname.lower()
    if lower.endswith(".png"):
        return MINI_PNG_1X1
    if lower.endswith(".bin"):
        return _lvgl_rgb565_placeholder(fname)
    raise ValueError(f"unsupported asset extension: {fname}")


def _c_escape_name(fname: str) -> str:
    return "".join(c if (c.isalnum() or c == "_") else "_" for c in fname)


def emit_c(out_path: Path, assets_bin: Path, manifest: list[str]) -> None:
    chunks: list[tuple[str, bytes]] = []
    for fname in manifest:
        chunks.append((fname, _load_or_placeholder(assets_bin, fname)))

    rows = []
    for fname, blob in chunks:
        sym = _c_escape_name(fname)
        hex_bytes = ",".join(f"0x{b:02x}" for b in blob)
        rows.append((fname, sym, hex_bytes, len(blob)))

    parts = []
    parts.append("// Auto-generated by gen_launcher_embedded_assets.py — do not edit.")
    parts.append('#include <stddef.h>')
    parts.append('#include <stdint.h>')
    parts.append('#include <string.h>')
    parts.append('#include <stdbool.h>')
    parts.append("")
    parts.append('#ifdef __cplusplus')
    parts.append('extern "C" {')
    parts.append('#endif')
    parts.append("")

    for _, sym, hex_bytes, _ in rows:
        parts.append(f"static const uint8_t stackchan_embed_sym_{sym}[] = {{{hex_bytes}}};\n")

    parts.append("")
    parts.append(
        """typedef struct {
    const char* name;
    const uint8_t* data;
    size_t length;
} stackchan_launcher_embedded_asset_t;
"""
    )
    parts.append(
        """static const stackchan_launcher_embedded_asset_t stackchan_launcher_embedded_assets[] = {"""
    )
    for fname, sym, _, ln in rows:
        parts.append(
            f'    {{"{fname}", stackchan_embed_sym_{sym}, {ln}}},'
        )
    parts.append("};")
    parts.append(
        """static const size_t stackchan_launcher_embedded_assets_count =
    sizeof(stackchan_launcher_embedded_assets) / sizeof(stackchan_launcher_embedded_assets[0]);

bool stackchan_launcher_embedded_lookup(const char* name,
                                        const uint8_t** out_data,
                                        size_t* out_length)
{
    if (!name || !out_data || !out_length) {
        return false;
    }
    for (size_t i = 0; i < stackchan_launcher_embedded_assets_count; i++) {
        if (strcmp(name, stackchan_launcher_embedded_assets[i].name) == 0) {
            *out_data = stackchan_launcher_embedded_assets[i].data;
            *out_length = stackchan_launcher_embedded_assets[i].length;
            return true;
        }
    }
    return false;
}
"""
    )

    parts.append('#ifdef __cplusplus')
    parts.append('}')
    parts.append('#endif')
    parts.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets-bin", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--manifest", nargs="*", help="Extra manifest entries")
    args = parser.parse_args()
    manifest = list(MANIFEST)
    if args.manifest:
        manifest.extend(args.manifest)

    emit_c(Path(args.out).resolve(), Path(args.assets_bin).resolve(), manifest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
